# Pipeline to deploy our infrastructure, build our application before deploying to our infrastructure


trigger:
- main

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
 imageName: julimage
 tag: '$(Build.BuildId)'
 rbendrg: "tf-rg-statefile"
 rbend: "jultfstorage"
 rbendcontainer: "jultfstate"
 rbendkey: "k8.terraform.tfstate"


stages:
  - stage: Terraform_Validate
    jobs:
      - job: Validate_code
        continueOnError: false
        steps:
          - template: ./tfvalidate-template.yml
                   
  - stage: Terraform_Deploy
    condition: succeeded('Terraform_Validate')
    dependsOn: Terraform_Validate
    jobs:
      - job: Terraform_apply
        steps:
          - template: ./tfdeploy-template.yml

  - stage: Docker_Build_and_Push 
    condition: succeeded('Terraform_Deploy')
    dependsOn:  Terraform_Deploy
    jobs:
      - job: Build_the_Image
        steps:
          - template: ./buildimage-template.yml 

  - stage: Deploy_to_AKS 
    condition: succeeded('Docker_Build_and_Push')
    dependsOn: Docker_Build_and_Push 
    jobs:
      - deployment: Deploy_To_AKS
        displayName: Deploy_To_AKS
        environment: 'k8prod.default'
        strategy:
         runOnce:
           deploy:
            steps:
            - template: ./deploy-AKS-template.yml 