apiVersion: apps/v1
kind: Deployment
metadata:
  name: julapp-deployment
  labels:
    app: julapp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: julapp
  template:
    metadata:
      labels:
        app: julapp
        tier: frontend
    spec:
      containers:
        - name: julapp
          image:  julacr.azurecr.io/julimage
          ports:
            - containerPort: 80
          

---

apiVersion: v1
kind: Service
metadata:
  name: julapp-service
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30000
    protocol: TCP
  selector: 
    app: julapp
    tier: frontend